In [1]:
from sklearn.datasets import load_breast_cancer
import numpy as np

In [2]:
data = load_breast_cancer()

In [35]:
X = data.data
y = data.target

In [9]:
mean=np.array([np.mean(X[:,i]) for i in range(X.shape[1])])

In [12]:
norm_X = X-mean

In [48]:
from sklearn.decomposition import PCA
import numpy as np
pca=PCA().fit(X)
print(pca.transform(X))

[[ 1.16014257e+03 -2.93917544e+02  4.85783976e+01 ...  1.29334919e-03
   1.98910417e-03  7.04378359e-04]
 [ 1.26912244e+03  1.56301818e+01 -3.53945342e+01 ... -1.34685217e-03
   6.85925212e-04 -1.06125086e-03]
 [ 9.95793889e+02  3.91567432e+01 -1.70975298e+00 ...  1.84867758e-05
  -7.75218581e-04  4.05360270e-04]
 ...
 [ 3.14501756e+02  4.75535252e+01 -1.04424072e+01 ...  2.54369638e-05
   4.83858890e-04 -2.85342703e-04]
 [ 1.12485812e+03  3.41292250e+01 -1.97420874e+01 ...  1.23547951e-03
  -8.08728730e-04  1.21655195e-03]
 [-7.71527622e+02 -8.86431064e+01  2.38890319e+01 ... -4.44552928e-03
   2.42876427e-04  1.46800350e-03]]


In [38]:
def pca(X, k):  # k is the components you want
    # mean of each feature
    n_samples, n_features = X.shape
    mean = np.array([np.mean(X[:, i]) for i in range(n_features)])
    # normalization
    norm_X = X - mean
    # scatter matrix
    scatter_matrix = np.dot(np.transpose(norm_X), norm_X)
    # Calculate the eigenvectors and eigenvalues
    eig_val, eig_vec = np.linalg.eig(scatter_matrix)
    eig_pairs = [(np.abs(eig_val[i]), eig_vec[:, i]) for i in range(n_features)]
    # sort eig_vec based on eig_val from highest to lowest
    eig_pairs.sort(reverse=True)
    # select the top k eig_vec
    feature = np.array([ele[1] for ele in eig_pairs[:k]])
    # get new data
    data = np.dot(norm_X, np.transpose(feature))
    return data

print(pca(X, 1))

[[ 1.16014257e+03]
 [ 1.26912244e+03]
 [ 9.95793889e+02]
 [-4.07180803e+02]
 [ 9.30341180e+02]
 [-2.11591259e+02]
 [ 8.21210900e+02]
 [-2.50899776e+01]
 [-1.91292834e+02]
 [-2.38292863e+02]
 [ 3.04687818e+02]
 [ 4.24361128e+02]
 [ 6.34514335e+02]
 [ 6.30426906e+01]
 [-1.96441210e+02]
 [ 5.60046828e+01]
 [ 2.35858120e+02]
 [ 4.47392780e+02]
 [ 1.61509345e+03]
 [-1.91621045e+02]
 [-2.85051275e+02]
 [-6.83583952e+02]
 [ 1.12560459e+02]
 [ 1.87373312e+03]
 [ 1.27373066e+03]
 [ 6.34879769e+02]
 [ 8.59184126e+00]
 [ 6.77784526e+02]
 [ 3.73719881e+02]
 [ 4.53678089e+02]
 [ 9.03981279e+02]
 [-1.03689312e+02]
 [ 5.24945203e+02]
 [ 1.06217159e+03]
 [ 4.04385934e+02]
 [ 4.10049756e+02]
 [-8.06577946e+01]
 [-3.55877850e+02]
 [-1.28973156e+02]
 [-1.70245723e+02]
 [-1.27994761e+02]
 [-4.62028008e+02]
 [ 8.97027427e+02]
 [-3.43752015e+01]
 [-1.84707363e+02]
 [ 8.07564573e+02]
 [-7.83838668e+02]
 [-1.66757183e+02]
 [-3.62699507e+02]
 [-2.05111744e+02]
 [-4.30034080e+02]
 [-2.35893530e+02]
 [-4.1646950

In [49]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [52]:
np.linalg.svd(x)

(array([[-0.21483724,  0.88723069,  0.40824829],
        [-0.52058739,  0.24964395, -0.81649658],
        [-0.82633754, -0.38794278,  0.40824829]]),
 array([1.68481034e+01, 1.06836951e+00, 4.41842475e-16]),
 array([[-0.47967118, -0.57236779, -0.66506441],
        [-0.77669099, -0.07568647,  0.62531805],
        [-0.40824829,  0.81649658, -0.40824829]]))